# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c49edc3964c7f475ccca5db9185a05a616f6f6b65481b7dbaff03b052784dfd37121a069d9dcc21ce9df7f0a0250c5b761bbab715d3fc234e4cb90e5fc6b1ef

test:
  secret_key_base: 8fb311c923e7f0e19ae91408aac8539f54d8a00ea626fcb311fa8e560b78d6c28a0840b66aeac18a5f61f2e33321bdb19bfd184e124cb29e025401bf29e721cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
